export const LOGO = 'logo'
export const USER_NAV_BARS = 'user_nav-bars'
export const USER_NAV_PROFILE = 'user-nav-profile'
export const HEART = 'heart'
export const HEART_RED = 'heart-red'
export const STAR = 'star'
export const SHARE = 'share'
export const SEARCH = 'search'
export const WHITE_HEART = 'heart-white'
export const RED_HEART = 'heart-red'

