// ************************************** ARROWS **************************************
export const ARROW_LEFT_FAT = 'ARROW_LEFT_FAT'
export const ARROW_LEFT = 'ARROW_LEFT'
export const ARROW_RIGHT_FAT = 'ARROW_RIGHT_FAT'
export const ARROW_RIGHT = 'ARROW_RIGHT'
export const ARROW_UP = 'ARROW_UP'

// ************************************** ... **************************************
export const LOGO = 'logo'
export const USER_NAV_BARS = 'user_nav-bars'
export const USER_NAV_PROFILE = 'user-nav-profile'
export const HEART_16 = 'heart-16'
export const RED_HEART_16 = 'heart-red-16'
export const STAR = 'star'
export const STAR_12 = 'star-12'
export const STAR_16 = 'star-16'
export const SHARE = 'share'
export const SEARCH = 'search'
export const SEARCH_2 = 'search-2'
export const WHITE_HEART = 'heart-white'
export const RED_HEART = 'heart-red'
export const LOCATION = 'location'
export const KEY = 'key'
export const EYE = 'eye'
export const RED_TAG = 'red-tag'
export const VERIFIED = 'verified'
export const CHECKIN = 'checkin'
export const TICK_DECLINE = 'tick-decline'
export const LEFT_ARROW = 'left-arrow'
export const SUPERHOST = 'superhost'
export const BLACK_SUPERHOST_16 = 'superhost-black-16'
